WAVEMQ:
    SiteRouter: "localhost:4516"
    EntityFile: "mortarent.ent"
    Namespace: "GyA1TN-RJ1DWOjdBV-_2BZDKSH0qOZLeHCwz-Dmpqqy0EA=="
    BaseURI: "mortar"
    ServerName: "mortar"

# service is on GyA1TN-RJ1DWOjdBV-_2BZDKSH0qOZLeHCwz-Dmpqqy0EA== mortar/s.grpcserver/mortarserver/i.grpc

HodConfig: "hodconfig.yml"
InfluxDBAddr: "http://127.0.0.1:8086"
InfluxDBUser: ""
InfluxDBPass: ""
ListenAddr: "127.0.0.1:4587"
PrometheusAddr: "127.0.0.1:9091"
