// Code generated by protoc-gen-go. DO NOT EDIT.
// source: iot.proto

package xbospb

/*
This is designed to be included by the main xbos proto file and includes the
definitions for the XBOS IoT devices

Maintainer: Gabe Fierro
Version 1.0
*/

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FanMode int32

const (
	FanMode_FanAuto FanMode = 0
	FanMode_FanOn   FanMode = 1
	FanMode_FanOff  FanMode = 2
)

var FanMode_name = map[int32]string{
	0: "FanAuto",
	1: "FanOn",
	2: "FanOff",
}
var FanMode_value = map[string]int32{
	"FanAuto": 0,
	"FanOn":   1,
	"FanOff":  2,
}

func (x FanMode) String() string {
	return proto.EnumName(FanMode_name, int32(x))
}
func (FanMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_iot_444d306d6094afc5, []int{0}
}

type HVACMode int32

const (
	HVACMode_HVACModeOff      HVACMode = 0
	HVACMode_HVACModeHeatOnly HVACMode = 1
	HVACMode_HVACModeCoolOnly HVACMode = 2
	HVACMode_HVACModeAuto     HVACMode = 3
)

var HVACMode_name = map[int32]string{
	0: "HVACModeOff",
	1: "HVACModeHeatOnly",
	2: "HVACModeCoolOnly",
	3: "HVACModeAuto",
}
var HVACMode_value = map[string]int32{
	"HVACModeOff":      0,
	"HVACModeHeatOnly": 1,
	"HVACModeCoolOnly": 2,
	"HVACModeAuto":     3,
}

func (x HVACMode) String() string {
	return proto.EnumName(HVACMode_name, int32(x))
}
func (HVACMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_iot_444d306d6094afc5, []int{1}
}

type HVACState int32

const (
	HVACState_HVACStateOff        HVACState = 0
	HVACState_HVACStateHeatStage1 HVACState = 1
	HVACState_HVACStateCoolStage1 HVACState = 2
	HVACState_HVACStateHeatStage2 HVACState = 3
	HVACState_HVACStateCoolStage2 HVACState = 4
)

var HVACState_name = map[int32]string{
	0: "HVACStateOff",
	1: "HVACStateHeatStage1",
	2: "HVACStateCoolStage1",
	3: "HVACStateHeatStage2",
	4: "HVACStateCoolStage2",
}
var HVACState_value = map[string]int32{
	"HVACStateOff":        0,
	"HVACStateHeatStage1": 1,
	"HVACStateCoolStage1": 2,
	"HVACStateHeatStage2": 3,
	"HVACStateCoolStage2": 4,
}

func (x HVACState) String() string {
	return proto.EnumName(HVACState_name, int32(x))
}
func (HVACState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_iot_444d306d6094afc5, []int{2}
}

type URI struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *URI) Reset()         { *m = URI{} }
func (m *URI) String() string { return proto.CompactTextString(m) }
func (*URI) ProtoMessage()    {}
func (*URI) Descriptor() ([]byte, []int) {
	return fileDescriptor_iot_444d306d6094afc5, []int{0}
}
func (m *URI) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_URI.Unmarshal(m, b)
}
func (m *URI) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_URI.Marshal(b, m, deterministic)
}
func (dst *URI) XXX_Merge(src proto.Message) {
	xxx_messageInfo_URI.Merge(dst, src)
}
func (m *URI) XXX_Size() int {
	return xxx_messageInfo_URI.Size(m)
}
func (m *URI) XXX_DiscardUnknown() {
	xxx_messageInfo_URI.DiscardUnknown(m)
}

var xxx_messageInfo_URI proto.InternalMessageInfo

func (m *URI) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *URI) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Triple struct {
	Subject              *URI     `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Predicate            *URI     `protobuf:"bytes,2,opt,name=predicate,proto3" json:"predicate,omitempty"`
	Object               *URI     `protobuf:"bytes,3,opt,name=object,proto3" json:"object,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Triple) Reset()         { *m = Triple{} }
func (m *Triple) String() string { return proto.CompactTextString(m) }
func (*Triple) ProtoMessage()    {}
func (*Triple) Descriptor() ([]byte, []int) {
	return fileDescriptor_iot_444d306d6094afc5, []int{1}
}
func (m *Triple) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Triple.Unmarshal(m, b)
}
func (m *Triple) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Triple.Marshal(b, m, deterministic)
}
func (dst *Triple) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Triple.Merge(dst, src)
}
func (m *Triple) XXX_Size() int {
	return xxx_messageInfo_Triple.Size(m)
}
func (m *Triple) XXX_DiscardUnknown() {
	xxx_messageInfo_Triple.DiscardUnknown(m)
}

var xxx_messageInfo_Triple proto.InternalMessageInfo

func (m *Triple) GetSubject() *URI {
	if m != nil {
		return m.Subject
	}
	return nil
}

func (m *Triple) GetPredicate() *URI {
	if m != nil {
		return m.Predicate
	}
	return nil
}

func (m *Triple) GetObject() *URI {
	if m != nil {
		return m.Object
	}
	return nil
}

type XBOSIoTDeviceState struct {
	// current time at device/service
	// unit:ns
	Time uint64 `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	// unique identifier for this request; used to line up with device state requests
	Requestid int64 `protobuf:"varint,2,opt,name=requestid,proto3" json:"requestid,omitempty"`
	// any error that occured since the last device report. If requestid above is non-zero,
	// then this error corresponds to the request with the given requestid
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	// XBOS IoT devices
	Thermostat               *Thermostat               `protobuf:"bytes,4,opt,name=thermostat,proto3" json:"thermostat,omitempty"`
	Meter                    *Meter                    `protobuf:"bytes,5,opt,name=meter,proto3" json:"meter,omitempty"`
	Light                    *Light                    `protobuf:"bytes,6,opt,name=light,proto3" json:"light,omitempty"`
	Evse                     *EVSE                     `protobuf:"bytes,7,opt,name=evse,proto3" json:"evse,omitempty"`
	WeatherStation           *WeatherStation           `protobuf:"bytes,8,opt,name=weather_station,json=weatherStation,proto3" json:"weather_station,omitempty"`
	WeatherStationPrediction *WeatherStationPrediction `protobuf:"bytes,9,opt,name=weather_station_prediction,json=weatherStationPrediction,proto3" json:"weather_station_prediction,omitempty"`
	ParkerState              *ParkerState              `protobuf:"bytes,10,opt,name=parker_state,json=parkerState,proto3" json:"parker_state,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}                  `json:"-"`
	XXX_unrecognized         []byte                    `json:"-"`
	XXX_sizecache            int32                     `json:"-"`
}

func (m *XBOSIoTDeviceState) Reset()         { *m = XBOSIoTDeviceState{} }
func (m *XBOSIoTDeviceState) String() string { return proto.CompactTextString(m) }
func (*XBOSIoTDeviceState) ProtoMessage()    {}
func (*XBOSIoTDeviceState) Descriptor() ([]byte, []int) {
	return fileDescriptor_iot_444d306d6094afc5, []int{2}
}
func (m *XBOSIoTDeviceState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XBOSIoTDeviceState.Unmarshal(m, b)
}
func (m *XBOSIoTDeviceState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XBOSIoTDeviceState.Marshal(b, m, deterministic)
}
func (dst *XBOSIoTDeviceState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XBOSIoTDeviceState.Merge(dst, src)
}
func (m *XBOSIoTDeviceState) XXX_Size() int {
	return xxx_messageInfo_XBOSIoTDeviceState.Size(m)
}
func (m *XBOSIoTDeviceState) XXX_DiscardUnknown() {
	xxx_messageInfo_XBOSIoTDeviceState.DiscardUnknown(m)
}

var xxx_messageInfo_XBOSIoTDeviceState proto.InternalMessageInfo

func (m *XBOSIoTDeviceState) GetTime() uint64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *XBOSIoTDeviceState) GetRequestid() int64 {
	if m != nil {
		return m.Requestid
	}
	return 0
}

func (m *XBOSIoTDeviceState) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *XBOSIoTDeviceState) GetThermostat() *Thermostat {
	if m != nil {
		return m.Thermostat
	}
	return nil
}

func (m *XBOSIoTDeviceState) GetMeter() *Meter {
	if m != nil {
		return m.Meter
	}
	return nil
}

func (m *XBOSIoTDeviceState) GetLight() *Light {
	if m != nil {
		return m.Light
	}
	return nil
}

func (m *XBOSIoTDeviceState) GetEvse() *EVSE {
	if m != nil {
		return m.Evse
	}
	return nil
}

func (m *XBOSIoTDeviceState) GetWeatherStation() *WeatherStation {
	if m != nil {
		return m.WeatherStation
	}
	return nil
}

func (m *XBOSIoTDeviceState) GetWeatherStationPrediction() *WeatherStationPrediction {
	if m != nil {
		return m.WeatherStationPrediction
	}
	return nil
}

func (m *XBOSIoTDeviceState) GetParkerState() *ParkerState {
	if m != nil {
		return m.ParkerState
	}
	return nil
}

type XBOSIoTDeviceActuation struct {
	// current time at device/service
	// unit:ns
	Time uint64 `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	// unique identifier for this request; used to line up with device state responses
	Requestid int64 `protobuf:"varint,2,opt,name=requestid,proto3" json:"requestid,omitempty"`
	// XBOS IoT devices
	Thermostat           *Thermostat `protobuf:"bytes,3,opt,name=thermostat,proto3" json:"thermostat,omitempty"`
	Meter                *Meter      `protobuf:"bytes,4,opt,name=meter,proto3" json:"meter,omitempty"`
	Light                *Light      `protobuf:"bytes,5,opt,name=light,proto3" json:"light,omitempty"`
	Evse                 *EVSE       `protobuf:"bytes,6,opt,name=evse,proto3" json:"evse,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *XBOSIoTDeviceActuation) Reset()         { *m = XBOSIoTDeviceActuation{} }
func (m *XBOSIoTDeviceActuation) String() string { return proto.CompactTextString(m) }
func (*XBOSIoTDeviceActuation) ProtoMessage()    {}
func (*XBOSIoTDeviceActuation) Descriptor() ([]byte, []int) {
	return fileDescriptor_iot_444d306d6094afc5, []int{3}
}
func (m *XBOSIoTDeviceActuation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XBOSIoTDeviceActuation.Unmarshal(m, b)
}
func (m *XBOSIoTDeviceActuation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XBOSIoTDeviceActuation.Marshal(b, m, deterministic)
}
func (dst *XBOSIoTDeviceActuation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XBOSIoTDeviceActuation.Merge(dst, src)
}
func (m *XBOSIoTDeviceActuation) XXX_Size() int {
	return xxx_messageInfo_XBOSIoTDeviceActuation.Size(m)
}
func (m *XBOSIoTDeviceActuation) XXX_DiscardUnknown() {
	xxx_messageInfo_XBOSIoTDeviceActuation.DiscardUnknown(m)
}

var xxx_messageInfo_XBOSIoTDeviceActuation proto.InternalMessageInfo

func (m *XBOSIoTDeviceActuation) GetTime() uint64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *XBOSIoTDeviceActuation) GetRequestid() int64 {
	if m != nil {
		return m.Requestid
	}
	return 0
}

func (m *XBOSIoTDeviceActuation) GetThermostat() *Thermostat {
	if m != nil {
		return m.Thermostat
	}
	return nil
}

func (m *XBOSIoTDeviceActuation) GetMeter() *Meter {
	if m != nil {
		return m.Meter
	}
	return nil
}

func (m *XBOSIoTDeviceActuation) GetLight() *Light {
	if m != nil {
		return m.Light
	}
	return nil
}

func (m *XBOSIoTDeviceActuation) GetEvse() *EVSE {
	if m != nil {
		return m.Evse
	}
	return nil
}

type XBOSIoTContext struct {
	// current time at device/service
	// unit:ns
	Time uint64 `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	// any triples this device wants to add about itself
	// these triples will be assumed to be generated by the entity
	// who has created/signed this message
	Context              []*Triple `protobuf:"bytes,2,rep,name=context,proto3" json:"context,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *XBOSIoTContext) Reset()         { *m = XBOSIoTContext{} }
func (m *XBOSIoTContext) String() string { return proto.CompactTextString(m) }
func (*XBOSIoTContext) ProtoMessage()    {}
func (*XBOSIoTContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_iot_444d306d6094afc5, []int{4}
}
func (m *XBOSIoTContext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XBOSIoTContext.Unmarshal(m, b)
}
func (m *XBOSIoTContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XBOSIoTContext.Marshal(b, m, deterministic)
}
func (dst *XBOSIoTContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XBOSIoTContext.Merge(dst, src)
}
func (m *XBOSIoTContext) XXX_Size() int {
	return xxx_messageInfo_XBOSIoTContext.Size(m)
}
func (m *XBOSIoTContext) XXX_DiscardUnknown() {
	xxx_messageInfo_XBOSIoTContext.DiscardUnknown(m)
}

var xxx_messageInfo_XBOSIoTContext proto.InternalMessageInfo

func (m *XBOSIoTContext) GetTime() uint64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *XBOSIoTContext) GetContext() []*Triple {
	if m != nil {
		return m.Context
	}
	return nil
}

// Thermostat
type Thermostat struct {
	// Current temperature recorded by thermostat
	// unit:celsius
	Temperature *Double `protobuf:"bytes,1,opt,name=temperature,proto3" json:"temperature,omitempty"`
	// unit:% rh
	RelativeHumidity *Double `protobuf:"bytes,2,opt,name=relative_humidity,json=relativeHumidity,proto3" json:"relative_humidity,omitempty"`
	// If true, then the thermostat is in override mode
	// unit: t/f
	Override *Bool `protobuf:"bytes,3,opt,name=override,proto3" json:"override,omitempty"`
	// If true, the fan is on; else it is off
	// unit: t/f
	FanState *Bool `protobuf:"bytes,4,opt,name=fan_state,json=fanState,proto3" json:"fan_state,omitempty"`
	// Current operating mode of the fan
	// unit: xbos/iot/FanMode
	FanMode FanMode `protobuf:"varint,5,opt,name=fan_mode,json=fanMode,proto3,enum=xbospb.FanMode" json:"fan_mode,omitempty"`
	// Current operating mode of the HVAC
	// unit: xbos/iot/HVACMode
	Mode HVACMode `protobuf:"varint,6,opt,name=mode,proto3,enum=xbospb.HVACMode" json:"mode,omitempty"`
	// Current HVAC state
	// unit: xbos/iot/HVACState
	State HVACState `protobuf:"varint,7,opt,name=state,proto3,enum=xbospb.HVACState" json:"state,omitempty"`
	// number of heat stages enabled
	EnabledHeatStages *Int32 `protobuf:"bytes,8,opt,name=enabled_heat_stages,json=enabledHeatStages,proto3" json:"enabled_heat_stages,omitempty"`
	// number of cool stages enabled
	EnabledCoolStages *Int32 `protobuf:"bytes,9,opt,name=enabled_cool_stages,json=enabledCoolStages,proto3" json:"enabled_cool_stages,omitempty"`
	// heating setpoint
	// unit: celsius
	HeatingSetpoint *Double `protobuf:"bytes,10,opt,name=heating_setpoint,json=heatingSetpoint,proto3" json:"heating_setpoint,omitempty"`
	// cooling setpoint
	// unit: celsius
	CoolingSetpoint      *Double  `protobuf:"bytes,11,opt,name=cooling_setpoint,json=coolingSetpoint,proto3" json:"cooling_setpoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Thermostat) Reset()         { *m = Thermostat{} }
func (m *Thermostat) String() string { return proto.CompactTextString(m) }
func (*Thermostat) ProtoMessage()    {}
func (*Thermostat) Descriptor() ([]byte, []int) {
	return fileDescriptor_iot_444d306d6094afc5, []int{5}
}
func (m *Thermostat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Thermostat.Unmarshal(m, b)
}
func (m *Thermostat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Thermostat.Marshal(b, m, deterministic)
}
func (dst *Thermostat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Thermostat.Merge(dst, src)
}
func (m *Thermostat) XXX_Size() int {
	return xxx_messageInfo_Thermostat.Size(m)
}
func (m *Thermostat) XXX_DiscardUnknown() {
	xxx_messageInfo_Thermostat.DiscardUnknown(m)
}

var xxx_messageInfo_Thermostat proto.InternalMessageInfo

func (m *Thermostat) GetTemperature() *Double {
	if m != nil {
		return m.Temperature
	}
	return nil
}

func (m *Thermostat) GetRelativeHumidity() *Double {
	if m != nil {
		return m.RelativeHumidity
	}
	return nil
}

func (m *Thermostat) GetOverride() *Bool {
	if m != nil {
		return m.Override
	}
	return nil
}

func (m *Thermostat) GetFanState() *Bool {
	if m != nil {
		return m.FanState
	}
	return nil
}

func (m *Thermostat) GetFanMode() FanMode {
	if m != nil {
		return m.FanMode
	}
	return FanMode_FanAuto
}

func (m *Thermostat) GetMode() HVACMode {
	if m != nil {
		return m.Mode
	}
	return HVACMode_HVACModeOff
}

func (m *Thermostat) GetState() HVACState {
	if m != nil {
		return m.State
	}
	return HVACState_HVACStateOff
}

func (m *Thermostat) GetEnabledHeatStages() *Int32 {
	if m != nil {
		return m.EnabledHeatStages
	}
	return nil
}

func (m *Thermostat) GetEnabledCoolStages() *Int32 {
	if m != nil {
		return m.EnabledCoolStages
	}
	return nil
}

func (m *Thermostat) GetHeatingSetpoint() *Double {
	if m != nil {
		return m.HeatingSetpoint
	}
	return nil
}

func (m *Thermostat) GetCoolingSetpoint() *Double {
	if m != nil {
		return m.CoolingSetpoint
	}
	return nil
}

type Meter struct {
	// unit: kW
	Power *Double `protobuf:"bytes,1,opt,name=power,proto3" json:"power,omitempty"`
	// unit: V
	Voltage *Double `protobuf:"bytes,2,opt,name=voltage,proto3" json:"voltage,omitempty"`
	// unit: kVA
	ApparentPower *Double `protobuf:"bytes,3,opt,name=apparent_power,json=apparentPower,proto3" json:"apparent_power,omitempty"`
	// unit: KWh
	Energy               *Double  `protobuf:"bytes,4,opt,name=energy,proto3" json:"energy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Meter) Reset()         { *m = Meter{} }
func (m *Meter) String() string { return proto.CompactTextString(m) }
func (*Meter) ProtoMessage()    {}
func (*Meter) Descriptor() ([]byte, []int) {
	return fileDescriptor_iot_444d306d6094afc5, []int{6}
}
func (m *Meter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Meter.Unmarshal(m, b)
}
func (m *Meter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Meter.Marshal(b, m, deterministic)
}
func (dst *Meter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Meter.Merge(dst, src)
}
func (m *Meter) XXX_Size() int {
	return xxx_messageInfo_Meter.Size(m)
}
func (m *Meter) XXX_DiscardUnknown() {
	xxx_messageInfo_Meter.DiscardUnknown(m)
}

var xxx_messageInfo_Meter proto.InternalMessageInfo

func (m *Meter) GetPower() *Double {
	if m != nil {
		return m.Power
	}
	return nil
}

func (m *Meter) GetVoltage() *Double {
	if m != nil {
		return m.Voltage
	}
	return nil
}

func (m *Meter) GetApparentPower() *Double {
	if m != nil {
		return m.ApparentPower
	}
	return nil
}

func (m *Meter) GetEnergy() *Double {
	if m != nil {
		return m.Energy
	}
	return nil
}

type Light struct {
	// True if the light is on
	// unit: on/off
	State *Bool `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	// 100 is maximum brightness
	Brightness           *Int64   `protobuf:"bytes,2,opt,name=brightness,proto3" json:"brightness,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Light) Reset()         { *m = Light{} }
func (m *Light) String() string { return proto.CompactTextString(m) }
func (*Light) ProtoMessage()    {}
func (*Light) Descriptor() ([]byte, []int) {
	return fileDescriptor_iot_444d306d6094afc5, []int{7}
}
func (m *Light) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Light.Unmarshal(m, b)
}
func (m *Light) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Light.Marshal(b, m, deterministic)
}
func (dst *Light) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Light.Merge(dst, src)
}
func (m *Light) XXX_Size() int {
	return xxx_messageInfo_Light.Size(m)
}
func (m *Light) XXX_DiscardUnknown() {
	xxx_messageInfo_Light.DiscardUnknown(m)
}

var xxx_messageInfo_Light proto.InternalMessageInfo

func (m *Light) GetState() *Bool {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *Light) GetBrightness() *Int64 {
	if m != nil {
		return m.Brightness
	}
	return nil
}

type EVSE struct {
	// maximum allowed current for charging
	// unit: A
	CurrentLimit *Double `protobuf:"bytes,1,opt,name=current_limit,json=currentLimit,proto3" json:"current_limit,omitempty"`
	// active charge current
	// unit: A
	Current *Double `protobuf:"bytes,2,opt,name=current,proto3" json:"current,omitempty"`
	// active charge voltage
	// unit: V
	Voltage *Double `protobuf:"bytes,3,opt,name=voltage,proto3" json:"voltage,omitempty"`
	// seconds left until car is charged
	// unit: seconds
	ChargingTimeLeft *Int32 `protobuf:"bytes,4,opt,name=charging_time_left,json=chargingTimeLeft,proto3" json:"charging_time_left,omitempty"`
	// charge state of the EVSE
	// unit: on/off
	State                *Bool    `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EVSE) Reset()         { *m = EVSE{} }
func (m *EVSE) String() string { return proto.CompactTextString(m) }
func (*EVSE) ProtoMessage()    {}
func (*EVSE) Descriptor() ([]byte, []int) {
	return fileDescriptor_iot_444d306d6094afc5, []int{8}
}
func (m *EVSE) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EVSE.Unmarshal(m, b)
}
func (m *EVSE) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EVSE.Marshal(b, m, deterministic)
}
func (dst *EVSE) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EVSE.Merge(dst, src)
}
func (m *EVSE) XXX_Size() int {
	return xxx_messageInfo_EVSE.Size(m)
}
func (m *EVSE) XXX_DiscardUnknown() {
	xxx_messageInfo_EVSE.DiscardUnknown(m)
}

var xxx_messageInfo_EVSE proto.InternalMessageInfo

func (m *EVSE) GetCurrentLimit() *Double {
	if m != nil {
		return m.CurrentLimit
	}
	return nil
}

func (m *EVSE) GetCurrent() *Double {
	if m != nil {
		return m.Current
	}
	return nil
}

func (m *EVSE) GetVoltage() *Double {
	if m != nil {
		return m.Voltage
	}
	return nil
}

func (m *EVSE) GetChargingTimeLeft() *Int32 {
	if m != nil {
		return m.ChargingTimeLeft
	}
	return nil
}

func (m *EVSE) GetState() *Bool {
	if m != nil {
		return m.State
	}
	return nil
}

type WeatherStation struct {
	// unit: celsius
	Temperature *Double `protobuf:"bytes,1,opt,name=temperature,proto3" json:"temperature,omitempty"`
	// unit: unknown
	Humidity *Double `protobuf:"bytes,2,opt,name=humidity,proto3" json:"humidity,omitempty"`
	// unit: km
	NearestStormDistance *Double `protobuf:"bytes,3,opt,name=nearest_storm_distance,json=nearestStormDistance,proto3" json:"nearest_storm_distance,omitempty"`
	// unit: degrees
	NearestStormBearing *Int32 `protobuf:"bytes,4,opt,name=nearest_storm_bearing,json=nearestStormBearing,proto3" json:"nearest_storm_bearing,omitempty"`
	// precip intensity
	// unit: unknown
	PrecipIntensity      *Double  `protobuf:"bytes,5,opt,name=precip_intensity,json=precipIntensity,proto3" json:"precip_intensity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WeatherStation) Reset()         { *m = WeatherStation{} }
func (m *WeatherStation) String() string { return proto.CompactTextString(m) }
func (*WeatherStation) ProtoMessage()    {}
func (*WeatherStation) Descriptor() ([]byte, []int) {
	return fileDescriptor_iot_444d306d6094afc5, []int{9}
}
func (m *WeatherStation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WeatherStation.Unmarshal(m, b)
}
func (m *WeatherStation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WeatherStation.Marshal(b, m, deterministic)
}
func (dst *WeatherStation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WeatherStation.Merge(dst, src)
}
func (m *WeatherStation) XXX_Size() int {
	return xxx_messageInfo_WeatherStation.Size(m)
}
func (m *WeatherStation) XXX_DiscardUnknown() {
	xxx_messageInfo_WeatherStation.DiscardUnknown(m)
}

var xxx_messageInfo_WeatherStation proto.InternalMessageInfo

func (m *WeatherStation) GetTemperature() *Double {
	if m != nil {
		return m.Temperature
	}
	return nil
}

func (m *WeatherStation) GetHumidity() *Double {
	if m != nil {
		return m.Humidity
	}
	return nil
}

func (m *WeatherStation) GetNearestStormDistance() *Double {
	if m != nil {
		return m.NearestStormDistance
	}
	return nil
}

func (m *WeatherStation) GetNearestStormBearing() *Int32 {
	if m != nil {
		return m.NearestStormBearing
	}
	return nil
}

func (m *WeatherStation) GetPrecipIntensity() *Double {
	if m != nil {
		return m.PrecipIntensity
	}
	return nil
}

type WeatherStationPrediction struct {
	Predictions          []*WeatherStationPrediction_Prediction `protobuf:"bytes,1,rep,name=predictions,proto3" json:"predictions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *WeatherStationPrediction) Reset()         { *m = WeatherStationPrediction{} }
func (m *WeatherStationPrediction) String() string { return proto.CompactTextString(m) }
func (*WeatherStationPrediction) ProtoMessage()    {}
func (*WeatherStationPrediction) Descriptor() ([]byte, []int) {
	return fileDescriptor_iot_444d306d6094afc5, []int{10}
}
func (m *WeatherStationPrediction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WeatherStationPrediction.Unmarshal(m, b)
}
func (m *WeatherStationPrediction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WeatherStationPrediction.Marshal(b, m, deterministic)
}
func (dst *WeatherStationPrediction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WeatherStationPrediction.Merge(dst, src)
}
func (m *WeatherStationPrediction) XXX_Size() int {
	return xxx_messageInfo_WeatherStationPrediction.Size(m)
}
func (m *WeatherStationPrediction) XXX_DiscardUnknown() {
	xxx_messageInfo_WeatherStationPrediction.DiscardUnknown(m)
}

var xxx_messageInfo_WeatherStationPrediction proto.InternalMessageInfo

func (m *WeatherStationPrediction) GetPredictions() []*WeatherStationPrediction_Prediction {
	if m != nil {
		return m.Predictions
	}
	return nil
}

type WeatherStationPrediction_Prediction struct {
	PredictionTime       uint64          `protobuf:"varint,1,opt,name=prediction_time,json=predictionTime,proto3" json:"prediction_time,omitempty"`
	Prediction           *WeatherStation `protobuf:"bytes,2,opt,name=prediction,proto3" json:"prediction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *WeatherStationPrediction_Prediction) Reset()         { *m = WeatherStationPrediction_Prediction{} }
func (m *WeatherStationPrediction_Prediction) String() string { return proto.CompactTextString(m) }
func (*WeatherStationPrediction_Prediction) ProtoMessage()    {}
func (*WeatherStationPrediction_Prediction) Descriptor() ([]byte, []int) {
	return fileDescriptor_iot_444d306d6094afc5, []int{10, 0}
}
func (m *WeatherStationPrediction_Prediction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WeatherStationPrediction_Prediction.Unmarshal(m, b)
}
func (m *WeatherStationPrediction_Prediction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WeatherStationPrediction_Prediction.Marshal(b, m, deterministic)
}
func (dst *WeatherStationPrediction_Prediction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WeatherStationPrediction_Prediction.Merge(dst, src)
}
func (m *WeatherStationPrediction_Prediction) XXX_Size() int {
	return xxx_messageInfo_WeatherStationPrediction_Prediction.Size(m)
}
func (m *WeatherStationPrediction_Prediction) XXX_DiscardUnknown() {
	xxx_messageInfo_WeatherStationPrediction_Prediction.DiscardUnknown(m)
}

var xxx_messageInfo_WeatherStationPrediction_Prediction proto.InternalMessageInfo

func (m *WeatherStationPrediction_Prediction) GetPredictionTime() uint64 {
	if m != nil {
		return m.PredictionTime
	}
	return 0
}

func (m *WeatherStationPrediction_Prediction) GetPrediction() *WeatherStation {
	if m != nil {
		return m.Prediction
	}
	return nil
}

type Weather_Current_State struct {
	// epoch time
	// unit: seconds
	Time *Int64 `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	// clear-day/clear-night/rain/snow/sleet/wind/fog/cloudy/partly-cloudy-day/partly-cloudy-night
	Icon string `protobuf:"bytes,2,opt,name=icon,proto3" json:"icon,omitempty"`
	// the approximate distance to the nearest storm
	// unit: miles
	NearestStormDistance *Double `protobuf:"bytes,3,opt,name=nearestStormDistance,proto3" json:"nearestStormDistance,omitempty"`
	// direction of the nearest storm with true north at 0 and progressing clockwise; if nearestStormDistance=0 then this value will not be defined
	// unit: degrees
	NearestStormBearing *Double `protobuf:"bytes,4,opt,name=nearestStormBearing,proto3" json:"nearestStormBearing,omitempty"`
	// intensity of precipitation occurring at the given time; this value is conditional on probability
	// unit: inches per hour
	PrecipIntensity *Double `protobuf:"bytes,5,opt,name=precipIntensity,proto3" json:"precipIntensity,omitempty"`
	// the standard deviation of the distribution of precipIntensity
	PrecipIntensityError *Double `protobuf:"bytes,6,opt,name=precipIntensityError,proto3" json:"precipIntensityError,omitempty"`
	// the probability of precipitation occurring; 0-1
	PrecipProbability *Double `protobuf:"bytes,7,opt,name=precipProbability,proto3" json:"precipProbability,omitempty"`
	// rain/snow/sleet; if precipIntensity is zero then this property will not be defined; due to the lack of data historical precipType information is usually estimated rather than observed
	PrecipType string `protobuf:"bytes,8,opt,name=precipType,proto3" json:"precipType,omitempty"`
	// air temperature
	// unit: F
	Temperature *Double `protobuf:"bytes,9,opt,name=temperature,proto3" json:"temperature,omitempty"`
	// feels-like temperature
	// unit: F
	ApparentTemperature *Double `protobuf:"bytes,10,opt,name=apparentTemperature,proto3" json:"apparentTemperature,omitempty"`
	// dew point temperature
	// unit: F
	DewPoint *Double `protobuf:"bytes,11,opt,name=dewPoint,proto3" json:"dewPoint,omitempty"`
	// relative humidity; 0-1
	Humidity *Double `protobuf:"bytes,12,opt,name=humidity,proto3" json:"humidity,omitempty"`
	// sea-level air pressure
	// unit: millibars
	Pressure *Double `protobuf:"bytes,13,opt,name=pressure,proto3" json:"pressure,omitempty"`
	// wind speed
	// unit: miles per hour
	WindSpeed *Double `protobuf:"bytes,14,opt,name=windSpeed,proto3" json:"windSpeed,omitempty"`
	// wind gust speed
	// unit: miles per hour
	WindGust *Double `protobuf:"bytes,15,opt,name=windGust,proto3" json:"windGust,omitempty"`
	// the direction that the wind is coming from with true north at 0 and progressing clockwise; if windSpeed=0 then this value will not be defined
	// unit: degree
	WindBearing *Double `protobuf:"bytes,16,opt,name=windBearing,proto3" json:"windBearing,omitempty"`
	// the percentage of sky occluded by clouds; 0-1
	CloudCover *Double `protobuf:"bytes,17,opt,name=cloudCover,proto3" json:"cloudCover,omitempty"`
	// uv index
	// unit: miles
	UvIndex *Double `protobuf:"bytes,18,opt,name=uvIndex,proto3" json:"uvIndex,omitempty"`
	// average visibility capped at 10 miles
	Visibility *Double `protobuf:"bytes,19,opt,name=visibility,proto3" json:"visibility,omitempty"`
	// the columnar density of total atmospheric ozone
	// unit: Dobson
	Ozone                *Double  `protobuf:"bytes,20,opt,name=ozone,proto3" json:"ozone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Weather_Current_State) Reset()         { *m = Weather_Current_State{} }
func (m *Weather_Current_State) String() string { return proto.CompactTextString(m) }
func (*Weather_Current_State) ProtoMessage()    {}
func (*Weather_Current_State) Descriptor() ([]byte, []int) {
	return fileDescriptor_iot_444d306d6094afc5, []int{11}
}
func (m *Weather_Current_State) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Weather_Current_State.Unmarshal(m, b)
}
func (m *Weather_Current_State) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Weather_Current_State.Marshal(b, m, deterministic)
}
func (dst *Weather_Current_State) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Weather_Current_State.Merge(dst, src)
}
func (m *Weather_Current_State) XXX_Size() int {
	return xxx_messageInfo_Weather_Current_State.Size(m)
}
func (m *Weather_Current_State) XXX_DiscardUnknown() {
	xxx_messageInfo_Weather_Current_State.DiscardUnknown(m)
}

var xxx_messageInfo_Weather_Current_State proto.InternalMessageInfo

func (m *Weather_Current_State) GetTime() *Int64 {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *Weather_Current_State) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *Weather_Current_State) GetNearestStormDistance() *Double {
	if m != nil {
		return m.NearestStormDistance
	}
	return nil
}

func (m *Weather_Current_State) GetNearestStormBearing() *Double {
	if m != nil {
		return m.NearestStormBearing
	}
	return nil
}

func (m *Weather_Current_State) GetPrecipIntensity() *Double {
	if m != nil {
		return m.PrecipIntensity
	}
	return nil
}

func (m *Weather_Current_State) GetPrecipIntensityError() *Double {
	if m != nil {
		return m.PrecipIntensityError
	}
	return nil
}

func (m *Weather_Current_State) GetPrecipProbability() *Double {
	if m != nil {
		return m.PrecipProbability
	}
	return nil
}

func (m *Weather_Current_State) GetPrecipType() string {
	if m != nil {
		return m.PrecipType
	}
	return ""
}

func (m *Weather_Current_State) GetTemperature() *Double {
	if m != nil {
		return m.Temperature
	}
	return nil
}

func (m *Weather_Current_State) GetApparentTemperature() *Double {
	if m != nil {
		return m.ApparentTemperature
	}
	return nil
}

func (m *Weather_Current_State) GetDewPoint() *Double {
	if m != nil {
		return m.DewPoint
	}
	return nil
}

func (m *Weather_Current_State) GetHumidity() *Double {
	if m != nil {
		return m.Humidity
	}
	return nil
}

func (m *Weather_Current_State) GetPressure() *Double {
	if m != nil {
		return m.Pressure
	}
	return nil
}

func (m *Weather_Current_State) GetWindSpeed() *Double {
	if m != nil {
		return m.WindSpeed
	}
	return nil
}

func (m *Weather_Current_State) GetWindGust() *Double {
	if m != nil {
		return m.WindGust
	}
	return nil
}

func (m *Weather_Current_State) GetWindBearing() *Double {
	if m != nil {
		return m.WindBearing
	}
	return nil
}

func (m *Weather_Current_State) GetCloudCover() *Double {
	if m != nil {
		return m.CloudCover
	}
	return nil
}

func (m *Weather_Current_State) GetUvIndex() *Double {
	if m != nil {
		return m.UvIndex
	}
	return nil
}

func (m *Weather_Current_State) GetVisibility() *Double {
	if m != nil {
		return m.Visibility
	}
	return nil
}

func (m *Weather_Current_State) GetOzone() *Double {
	if m != nil {
		return m.Ozone
	}
	return nil
}

func init() {
	proto.RegisterType((*URI)(nil), "xbospb.URI")
	proto.RegisterType((*Triple)(nil), "xbospb.Triple")
	proto.RegisterType((*XBOSIoTDeviceState)(nil), "xbospb.XBOSIoTDeviceState")
	proto.RegisterType((*XBOSIoTDeviceActuation)(nil), "xbospb.XBOSIoTDeviceActuation")
	proto.RegisterType((*XBOSIoTContext)(nil), "xbospb.XBOSIoTContext")
	proto.RegisterType((*Thermostat)(nil), "xbospb.Thermostat")
	proto.RegisterType((*Meter)(nil), "xbospb.Meter")
	proto.RegisterType((*Light)(nil), "xbospb.Light")
	proto.RegisterType((*EVSE)(nil), "xbospb.EVSE")
	proto.RegisterType((*WeatherStation)(nil), "xbospb.WeatherStation")
	proto.RegisterType((*WeatherStationPrediction)(nil), "xbospb.WeatherStationPrediction")
	proto.RegisterType((*WeatherStationPrediction_Prediction)(nil), "xbospb.WeatherStationPrediction.Prediction")
	proto.RegisterType((*Weather_Current_State)(nil), "xbospb.Weather_Current_State")
	proto.RegisterEnum("xbospb.FanMode", FanMode_name, FanMode_value)
	proto.RegisterEnum("xbospb.HVACMode", HVACMode_name, HVACMode_value)
	proto.RegisterEnum("xbospb.HVACState", HVACState_name, HVACState_value)
}

func init() { proto.RegisterFile("iot.proto", fileDescriptor_iot_444d306d6094afc5) }

var fileDescriptor_iot_444d306d6094afc5 = []byte{
	// 1355 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x97, 0x5d, 0x6f, 0x1b, 0x45,
	0x17, 0xc7, 0xeb, 0xf7, 0xf8, 0x38, 0x71, 0x36, 0xe3, 0xb4, 0xcf, 0x2a, 0x7a, 0x84, 0x82, 0x5b,
	0x68, 0x08, 0x34, 0xa2, 0x2e, 0x54, 0x54, 0x05, 0xd1, 0xbc, 0xb4, 0x34, 0x52, 0x4b, 0xa3, 0x75,
	0x5a, 0x5e, 0x2e, 0xb0, 0xd6, 0xeb, 0xe3, 0x64, 0x60, 0xbd, 0xb3, 0xcc, 0x8e, 0x9d, 0x86, 0x1b,
	0xc4, 0x57, 0xe2, 0x82, 0x5b, 0x3e, 0x05, 0x12, 0x1f, 0x80, 0x2b, 0xae, 0xf8, 0x08, 0x68, 0x5e,
	0x76, 0xbd, 0x76, 0xc7, 0x49, 0xcb, 0xdd, 0xce, 0xfc, 0x7f, 0xe7, 0xcc, 0xcb, 0x99, 0x33, 0x67,
	0x16, 0xea, 0x94, 0x89, 0x9d, 0x98, 0x33, 0xc1, 0x48, 0xf5, 0x65, 0x9f, 0x25, 0x71, 0x7f, 0xa3,
	0x15, 0x8d, 0xc3, 0xd0, 0xef, 0x87, 0x28, 0xce, 0x63, 0x4c, 0xb4, 0xb8, 0xb1, 0x1c, 0xfb, 0xfc,
	0x07, 0xe4, 0xba, 0xd5, 0xbe, 0x07, 0xa5, 0xe7, 0xde, 0x21, 0xf9, 0x3f, 0xd4, 0x23, 0x7f, 0x84,
	0x49, 0xec, 0x07, 0xe8, 0x16, 0x36, 0x0b, 0x5b, 0x75, 0x6f, 0xda, 0x41, 0xd6, 0xa1, 0x32, 0xf1,
	0xc3, 0x31, 0xba, 0x45, 0xa5, 0xe8, 0x46, 0xfb, 0x67, 0xa8, 0x1e, 0x73, 0x1a, 0x87, 0x48, 0xde,
	0x81, 0x5a, 0x32, 0xee, 0x7f, 0x8f, 0x81, 0x50, 0xb6, 0x8d, 0x4e, 0x63, 0x47, 0xcf, 0x60, 0xe7,
	0xb9, 0x77, 0xe8, 0xa5, 0x1a, 0x79, 0x0f, 0xea, 0x31, 0xc7, 0x01, 0x0d, 0x7c, 0xa1, 0x5d, 0xcd,
	0x81, 0x53, 0x95, 0x5c, 0x87, 0x2a, 0xd3, 0x0e, 0x4b, 0xaf, 0x72, 0x46, 0x6a, 0xff, 0x51, 0x02,
	0xf2, 0xf5, 0xde, 0xb3, 0xee, 0x21, 0x3b, 0x3e, 0xc0, 0x09, 0x0d, 0xb0, 0x2b, 0xa4, 0x2d, 0x81,
	0xb2, 0xa0, 0x23, 0xbd, 0x8c, 0xb2, 0xa7, 0xbe, 0xe5, 0xfa, 0x38, 0xfe, 0x38, 0xc6, 0x44, 0xd0,
	0x81, 0x1a, 0xba, 0xe4, 0x4d, 0x3b, 0xe4, 0xfa, 0x90, 0x73, 0xc6, 0xd5, 0x60, 0x75, 0x4f, 0x37,
	0x48, 0x07, 0x40, 0x9c, 0x22, 0x1f, 0xb1, 0x44, 0xf8, 0xc2, 0x2d, 0xab, 0x79, 0x90, 0x74, 0x1e,
	0xc7, 0x99, 0xe2, 0xe5, 0x28, 0x72, 0x1d, 0x2a, 0x23, 0x14, 0xc8, 0xdd, 0x8a, 0xc2, 0x57, 0x52,
	0xfc, 0xa9, 0xec, 0xf4, 0xb4, 0x26, 0xa1, 0x90, 0x9e, 0x9c, 0x0a, 0xb7, 0x3a, 0x0b, 0x3d, 0x91,
	0x9d, 0x9e, 0xd6, 0xc8, 0x26, 0x94, 0x71, 0x92, 0xa0, 0x5b, 0x53, 0xcc, 0x72, 0xca, 0x3c, 0x7c,
	0xd1, 0x7d, 0xe8, 0x29, 0x85, 0x7c, 0x0e, 0xab, 0x67, 0xe8, 0xcb, 0xc1, 0x7b, 0x72, 0x6c, 0xca,
	0x22, 0x77, 0x49, 0xc1, 0xd7, 0x52, 0xf8, 0x2b, 0x2d, 0x77, 0xb5, 0xea, 0x35, 0xcf, 0x66, 0xda,
	0xe4, 0x3b, 0xd8, 0x98, 0x73, 0xd0, 0xd3, 0x11, 0x50, 0xbe, 0xea, 0xca, 0xd7, 0xa6, 0xdd, 0xd7,
	0x51, 0xc6, 0x79, 0xee, 0xd9, 0x02, 0x85, 0xdc, 0x05, 0x73, 0xd6, 0x94, 0x7b, 0x74, 0x41, 0x79,
	0x6c, 0xa5, 0x1e, 0x8f, 0x94, 0xa6, 0x62, 0xe6, 0x35, 0xe2, 0x69, 0xa3, 0xfd, 0x77, 0x01, 0xae,
	0xcd, 0xc4, 0x75, 0x37, 0x10, 0x63, 0x3d, 0xe5, 0x37, 0x8f, 0xed, 0x6c, 0x14, 0x4b, 0x6f, 0x16,
	0xc5, 0xf2, 0xeb, 0x44, 0xb1, 0xf2, 0x1a, 0x51, 0xac, 0x2e, 0x8a, 0x62, 0xfb, 0x4b, 0x68, 0x9a,
	0xb5, 0xee, 0xb3, 0x48, 0xe0, 0x4b, 0x61, 0x5d, 0xe3, 0x16, 0xd4, 0x02, 0x2d, 0xbb, 0xc5, 0xcd,
	0xd2, 0x56, 0xa3, 0xd3, 0xcc, 0x96, 0xa0, 0x52, 0xd0, 0x4b, 0xe5, 0xf6, 0xef, 0x65, 0x80, 0xe9,
	0xb2, 0xc8, 0x87, 0xd0, 0x10, 0x38, 0x8a, 0x91, 0xfb, 0x62, 0xcc, 0xd1, 0xa4, 0x67, 0x66, 0x7c,
	0xc0, 0xc6, 0xfd, 0x10, 0xbd, 0x3c, 0x42, 0xee, 0xc3, 0x1a, 0xc7, 0xd0, 0x17, 0x74, 0x82, 0xbd,
	0xd3, 0xf1, 0x88, 0x0e, 0xa8, 0x38, 0x37, 0xd9, 0x3a, 0x6f, 0xe7, 0xa4, 0xe0, 0x63, 0xc3, 0x91,
	0x2d, 0x58, 0x62, 0x13, 0xe4, 0x9c, 0x0e, 0xd0, 0xec, 0x75, 0xb6, 0xe6, 0x3d, 0xc6, 0x42, 0x2f,
	0x53, 0xe5, 0x65, 0x30, 0xf4, 0x23, 0x73, 0x32, 0xca, 0x36, 0x74, 0xe8, 0x47, 0x3a, 0xa1, 0xb7,
	0x41, 0x7e, 0xf7, 0x46, 0x6c, 0x80, 0x6a, 0xb3, 0x9b, 0x9d, 0xd5, 0x94, 0x7c, 0xe4, 0x47, 0x4f,
	0xd9, 0x00, 0xbd, 0xda, 0x50, 0x7f, 0x90, 0x1b, 0x50, 0x56, 0x5c, 0x55, 0x71, 0x4e, 0xca, 0x3d,
	0x7e, 0xb1, 0xbb, 0xaf, 0x40, 0xa5, 0x92, 0x9b, 0x50, 0xd1, 0x03, 0xd7, 0x14, 0xb6, 0x96, 0xc7,
	0xf4, 0x81, 0xd4, 0x3a, 0xf9, 0x0c, 0x5a, 0x18, 0xc9, 0x1b, 0x74, 0xd0, 0x3b, 0x45, 0x5f, 0xc8,
	0xe9, 0x9e, 0x60, 0x62, 0xf2, 0x2c, 0x0b, 0xf9, 0x61, 0x24, 0xee, 0x74, 0xbc, 0x35, 0x43, 0x3e,
	0x46, 0x5f, 0x74, 0x15, 0x97, 0x37, 0x0f, 0x18, 0x0b, 0x53, 0xf3, 0xfa, 0x45, 0xe6, 0xfb, 0x8c,
	0x85, 0xc6, 0xfc, 0x1e, 0x38, 0x72, 0x54, 0x1a, 0x9d, 0xf4, 0x12, 0x14, 0x31, 0xa3, 0x91, 0x30,
	0x49, 0x34, 0x1f, 0x89, 0x55, 0xc3, 0x75, 0x0d, 0x26, 0x4d, 0xe5, 0x88, 0x33, 0xa6, 0x0d, 0xbb,
	0xa9, 0xe1, 0x52, 0xd3, 0xf6, 0x6f, 0x05, 0xa8, 0xa8, 0x93, 0x4e, 0x6e, 0x40, 0x25, 0x66, 0x67,
	0xc8, 0x17, 0x1c, 0x1b, 0x2d, 0xca, 0xb3, 0x39, 0x61, 0xa1, 0x9c, 0xf1, 0x82, 0x63, 0x92, 0xca,
	0xe4, 0x63, 0x68, 0xfa, 0x71, 0xec, 0x73, 0x8c, 0x44, 0x4f, 0x3b, 0x2e, 0x59, 0x0d, 0x56, 0x52,
	0xea, 0x48, 0x0d, 0xf0, 0x2e, 0x54, 0x31, 0x42, 0x7e, 0x72, 0x6e, 0xce, 0xc9, 0x3c, 0x6e, 0xd4,
	0xf6, 0xb7, 0x50, 0x51, 0xc9, 0x47, 0xda, 0x69, 0x78, 0x0b, 0x96, 0x73, 0x65, 0x22, 0x7b, 0x0b,
	0xa0, 0xcf, 0x25, 0x1d, 0x61, 0x92, 0x98, 0x89, 0xe7, 0x23, 0x72, 0xf7, 0x23, 0x2f, 0x07, 0xb4,
	0xff, 0x29, 0x40, 0x59, 0x66, 0x2d, 0xb9, 0x03, 0x2b, 0xc1, 0x98, 0xab, 0x25, 0x84, 0x74, 0x44,
	0xc5, 0x82, 0xbd, 0x59, 0x36, 0xd0, 0x13, 0xc9, 0xa8, 0xf4, 0xd5, 0xed, 0x45, 0x5b, 0x64, 0xe4,
	0xfc, 0x66, 0x96, 0x2e, 0xde, 0xcc, 0xfb, 0x40, 0x82, 0x53, 0x9f, 0x9f, 0xc8, 0x10, 0xcb, 0x3b,
	0xa2, 0x17, 0xe2, 0x50, 0xcc, 0xdf, 0x58, 0xfa, 0x68, 0x39, 0x29, 0x78, 0x4c, 0x47, 0xf8, 0x04,
	0x87, 0xb9, 0x1d, 0xaa, 0x2c, 0xdc, 0xa1, 0xf6, 0xaf, 0x45, 0x68, 0xce, 0xde, 0xfa, 0xff, 0xe1,
	0x36, 0xd9, 0x86, 0xa5, 0x4b, 0x2e, 0x91, 0x4c, 0x27, 0x07, 0x70, 0x2d, 0x42, 0x9f, 0x63, 0x22,
	0xf3, 0x8c, 0xf1, 0x51, 0x6f, 0x40, 0x13, 0xe1, 0x47, 0xc1, 0xa2, 0xad, 0x58, 0x37, 0x74, 0x57,
	0xc2, 0x07, 0x86, 0x25, 0xbb, 0x70, 0x75, 0xd6, 0x4b, 0x1f, 0x7d, 0x4e, 0xa3, 0x13, 0xfb, 0xd6,
	0xb4, 0xf2, 0x3e, 0xf6, 0x34, 0x29, 0x93, 0x27, 0xe6, 0x18, 0xd0, 0xb8, 0x47, 0x23, 0x81, 0x51,
	0x22, 0x27, 0x5f, 0xb1, 0x27, 0x8f, 0xe6, 0x0e, 0x53, 0xac, 0xfd, 0x67, 0x01, 0xdc, 0x45, 0xa5,
	0x92, 0x3c, 0x85, 0xc6, 0xb4, 0xc0, 0x26, 0x6e, 0x41, 0xdd, 0xe4, 0xef, 0x5f, 0x56, 0x61, 0x77,
	0x72, 0xc5, 0x36, 0x6f, 0xbf, 0x31, 0x02, 0xc8, 0x39, 0xbf, 0x09, 0xab, 0x53, 0xb1, 0x97, 0xab,
	0x20, 0xcd, 0x69, 0xb7, 0x8c, 0x3f, 0xb9, 0x0b, 0x90, 0x2b, 0xf3, 0xc5, 0x0b, 0x9f, 0x0c, 0x39,
	0xb2, 0xfd, 0x57, 0x0d, 0xae, 0x1a, 0xb9, 0xb7, 0x6f, 0x52, 0x40, 0x5f, 0xd0, 0x6f, 0xe7, 0x2a,
	0xd6, 0x2b, 0x59, 0xa4, 0x0b, 0x18, 0x81, 0x32, 0x0d, 0xcc, 0x70, 0x75, 0x4f, 0x7d, 0x93, 0x3d,
	0xb0, 0x46, 0xf0, 0x8d, 0xa2, 0xfd, 0x00, 0x6c, 0x11, 0x5c, 0x70, 0x51, 0x58, 0x83, 0xfd, 0x09,
	0xcc, 0x07, 0xf1, 0x35, 0x63, 0x2d, 0xe7, 0x3f, 0xd7, 0xf5, 0x50, 0xbd, 0x22, 0xab, 0xf6, 0xf9,
	0xdb, 0x58, 0xf2, 0x29, 0xac, 0xe9, 0xfe, 0x23, 0xce, 0xfa, 0x7e, 0x9f, 0x86, 0x72, 0xfc, 0x9a,
	0xd5, 0xc1, 0xab, 0x20, 0x79, 0x4b, 0x85, 0x32, 0xa0, 0xf1, 0xf1, 0x79, 0x8c, 0xaa, 0x2a, 0xd5,
	0xbd, 0x5c, 0xcf, 0x7c, 0xbe, 0xd6, 0x2f, 0xcf, 0xd7, 0x07, 0xd0, 0x4a, 0x2f, 0xdf, 0xe3, 0x9c,
	0xa5, 0xbd, 0xea, 0xd8, 0x50, 0x99, 0xf1, 0x03, 0x3c, 0x3b, 0xba, 0xa0, 0xe2, 0x64, 0xfa, 0xcc,
	0xed, 0xb0, 0x7c, 0xc9, 0xed, 0xb0, 0x0d, 0x4b, 0x31, 0xc7, 0x24, 0x91, 0xd3, 0x59, 0xb1, 0xb3,
	0xa9, 0x4e, 0x3e, 0x80, 0xfa, 0x19, 0x8d, 0x06, 0xdd, 0x18, 0x71, 0xe0, 0x36, 0xad, 0xf0, 0x14,
	0x90, 0x9e, 0x65, 0xe3, 0x8b, 0x71, 0x22, 0xdc, 0x55, 0xbb, 0xe7, 0x54, 0x97, 0x3b, 0x2a, 0xbf,
	0xd3, 0x73, 0xe6, 0xd8, 0x77, 0x34, 0x87, 0x90, 0x1d, 0x80, 0x20, 0x64, 0xe3, 0xc1, 0xbe, 0x7c,
	0xfa, 0xb8, 0x6b, 0x56, 0x83, 0x1c, 0x21, 0x2b, 0xc0, 0x78, 0x72, 0x18, 0x0d, 0xf0, 0xa5, 0x4b,
	0xec, 0x15, 0xc0, 0xc8, 0xd2, 0xf3, 0x84, 0x26, 0xd4, 0x1c, 0x9a, 0x96, 0xdd, 0xf3, 0x94, 0x90,
	0xe5, 0x9c, 0xfd, 0xc4, 0x22, 0x74, 0xd7, 0xed, 0xe5, 0x5c, 0x89, 0xdb, 0xb7, 0xa0, 0x66, 0x5e,
	0x55, 0xa4, 0xa1, 0x3e, 0x77, 0xc7, 0x82, 0x39, 0x57, 0x48, 0x1d, 0x2a, 0x8f, 0xfc, 0xe8, 0x59,
	0xe4, 0x14, 0x08, 0x40, 0x55, 0x7e, 0x0e, 0x87, 0x4e, 0x71, 0xfb, 0x1b, 0x58, 0x4a, 0x1f, 0x57,
	0x64, 0x15, 0x1a, 0xe9, 0xb7, 0x14, 0xaf, 0x90, 0x75, 0x70, 0xd2, 0x0e, 0xf9, 0x2a, 0x7a, 0x16,
	0x85, 0xe7, 0x4e, 0x21, 0xdf, 0x2b, 0x1f, 0x3b, 0xaa, 0xb7, 0x48, 0x1c, 0x58, 0x4e, 0x7b, 0xd5,
	0x88, 0xa5, 0xed, 0x5f, 0x0a, 0x50, 0xcf, 0x5e, 0x64, 0xa9, 0xae, 0x1a, 0xda, 0xfb, 0xff, 0xa0,
	0x95, 0xf5, 0x64, 0x8f, 0xae, 0xdb, 0x4e, 0x61, 0x46, 0xc8, 0x9e, 0x53, 0xb7, 0x9d, 0xa2, 0xdd,
	0xa2, 0xe3, 0x94, 0xec, 0x16, 0x1d, 0xa7, 0xdc, 0xaf, 0xaa, 0xdf, 0xe4, 0x3b, 0xff, 0x06, 0x00,
	0x00, 0xff, 0xff, 0xf5, 0xd2, 0xda, 0x4e, 0x5e, 0x0f, 0x00, 0x00,
}
